### ISSUE TITLE
Use of undefined constant ext

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Plugins/downloads#11]
Posted by Remy on Geeklog Forum: https://www.geeklog.net/forum/viewtopic.php?showtopic=96943

After installing the latest downloads plugin a message appears in the error log:

`Sat Jan 12 19:22:57 2019 - 46.119.122.127 - E_WARNING(2) - Use of undefined constant ext - assumed 'ext' (this will throw an Error in a future version of PHP) @ .../plugins/downloads/include/functions.php line 415 `

Corresponding code:

```
$len = strlen(ext);
$modurl = substr($url, 0, -$len) . $ext;
```

I do assume it's a typo.
Yes, I'm on php 7.2

**Comment by P2Tera** [comment]
$len = strlen(ext); -> $len = strlen($ext);
This part check file extention of File Image.
$url is full path.
function DLM_modTNPath($url)
{
    $parts = pathinfo($url);
    $extary = array('jpg', 'png');
    foreach ($extary as $ext) {
        $len = strlen($ext);
        $modurl = substr($url, 0, -$len) . $ext;
        if (file_exists($modurl)) {
            return $modurl;
        }
    }
    return $url;
}
