### ISSUE TITLE
Improve Failed Download Attempts Error Log

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Plugins/downloads#16]
Geeklog.net gets a lot of invalid download attempts. The error message doesn't list the user id (I assume it is 1) and the file id is missing. I am not sure if it is because the actual id does not exist (the bot made it up) or what. Probably should include the made up one anyways (and maybe indicate it doesn't exisit).

I also think these type of downloads errors since they are so many and are not technically an error by the downloads plugin should be moved to their own log file as not to clutter up the important error.log file.

`Fri 06 Dec 2019 07:46:49 EST - 144.76.96.236 - Downloads: invalid attempt to download a file. User:, IP:144.76.96.236, File ID: `

**Comment by mystralkk** [comment]
With change sets 84ca3b4 and f3bd701, error handling is improved.
