### ISSUE TITLE
System Messages not displaying correctly on save of an Edit

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Plugins/downloads#17]
On Geeklog.net with Geeklog v2.2.1 Beta 4 installed when I edited the Old Beta 3 Geeklog download and switched it to a different category (From Geeklog to Geeklog->Old Version) I got the following message on save.

```
System Message - 12/18 11:06am

101

```

The Edit saved fine but the system message just said 101.

Here is the final url of the edit: https://www.geeklog.net/downloads/index.php?msg=101

I don't remember this happening when I did the same for the beta 2 release (updated the category) when I added the beta 3 release. So did a change from Geeklog v2.2.1 Beta 3 to Beta 4 cause the system message not to display correctly or is this just an older bug I didn't notice before?

**Comment by mystralkk** [comment]
Fixed with change set 2b0a260.  This bug was caused since COM_showMessage didn't treat a numeric string properly.
