### ISSUE TITLE
SQL Error when searching in admin list

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Plugins/downloads#2]
Got the following error when I searched for the word "themes" with no quotes in the downloads admin for the list. (on geeklog.net)

E_USER_ERROR(256) - An SQL error has occurred. Please see error.log for details. @ /.../system/databases/mysqli.class.php line 279

Call Stack # Function File Line
1 trigger_error /.../system/databases/mysqli.class.php 279 
2 dbQuery /.../system/lib-database.php 213
3 DB_query /.../system/lib-admin.php 476
4 ADMIN_list /.../admin/plugins/downloads/index.php 122
5 listDownloads /.../admin/plugins/downloads/index.php 618

SELECT lid, url, a.title, a.cid, date, version, size, b.owner_id, group_id, perm_owner, perm_group, perm_members, perm_anon FROM downloads a LEFT JOIN downloadcategories b ON a.cid=b.cid WHERE lid != ''  AND (title LIKE '%theme%')

**Comment by dengenxp** [comment]
Fixed with change set 16395fe
