### ISSUE TITLE
Rating a Download can cause a SQL Error

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Plugins/downloads#20]
Noticed the following errors in the geeklog.net error.log file. Not sure how it happened as I can rate a download fine. Looks like we should check ratinghostname variable before the insert happens.

> Tue 03 Mar 2020 12:32:35 EST - 197.62.57.221 - 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' '197.62.57.221', 1583256755)' at line 1 in /public_html/downloads/ratefile.php:102. SQL in question: INSERT INTO downloadvotes (lid, ratinguser, rating, ratinghostname, ratingtimestamp) VALUES ('file_geeklog-2.2.1', 1, , '197.62.57.221', 1583256755)  
> Tue 03 Mar 2020 12:32:35 EST - 197.62.57.221 - E_USER_ERROR(256) - An SQL error has occurred. Please see error.log for details. @ /system/databases/mysqli.class.php line 468  
>

**Comment by mystralkk** [comment]
Fixed with change set b8ccf85
